In [1]:
import pandas as pd
import os

In [15]:
os.listdir("../data/voter_turnout")

['vote04b_2022.xlsx']

In [16]:
df = pd.read_excel("../data/voter_turnout/vote04b_2022.xlsx", header = [0, 1], index_col = [0, 1])

In [17]:
df.head()

Characteristics                          Total population  \
                                       Unnamed: 2_level_1
UNITED STATES Total                                255457
              Male                                 124329
              Female                               131128
              White alone                          196926
              White non-Hispanic alone             157737

Characteristics                        Total citizen population  \
                                             Unnamed: 3_level_1
UNITED STATES Total                                      233546
              Male                                       112996
              Female                                     120549
              White alone                                182214
              White non-Hispanic alone                   154963

Characteristics                              Registered  \
                                       Total registered
UNITED STATES Total                              161422
              Male                                77021
              Female                              84401
              White alone                        129133
              White non-Hispanic alone           113427

Characteristics                                                     \
                                       Percent registered\n(Total)
UNITED STATES Total                                           63.2
              Male                                            61.9
              Female                                          64.4
              White alone                                     65.6
              White non-Hispanic alone                        71.9

Characteristics                                          \
                                       Margin of error1
UNITED STATES Total                                 0.5
              Male                                  0.6
              Female                                0.5
              White alone                           0.5
              White non-Hispanic alone              0.5

Characteristics                                                       \
                                       Percent registered\n(Citizen)
UNITED STATES Total                                             69.1
              Male                                              68.2
              Female                                            70.0
              White alone                                       70.9
              White non-Hispanic alone                          73.2

Characteristics                                                 Voted  \
                                       Margin of error1.1 Total voted
UNITED STATES Total                                   0.5      121916
              Male                                    0.6       57966
              Female                                  0.5       63950
              White alone                             0.5       99600
              White non-Hispanic alone                0.5       89318

Characteristics                                                \
                                       Percent voted\n(Total)
UNITED STATES Total                                      47.7
              Male                                       46.6
              Female                                     48.8
              White alone                                50.6
              White non-Hispanic alone                   56.6

Characteristics                                          \
                                       Margin of error1
UNITED STATES Total                                 0.5
              Male                                  0.6
              Female                                0.5
              White alone                           0.5
              White non-Hispanic alone              0.6

Characteristics                                                  \
                                       Percent voted\n(Citizen)
UNITED STATES Total                                        52.2
              Male                                         51.3
              Female                                       53.0
              White alone                                  54.7
              White non-Hispanic alone                     57.6

Characteristics
                                       Margin of error1.1
UNITED STATES Total                                   0.5
              Male                                    0.6
              Female                                  0.6
              White alone                             0.5
              White non-Hispanic alone                0.6

In [25]:
turnout = df[('Voted', 'Total voted')] / df[('Registered', 'Total registered')]
turnout = turnout.reset_index()

In [28]:
turnout.columns = ['geo', 'group', 'turnout']

In [30]:
turnout['group'].unique()

array(['Total', 'Male', 'Female', 'White alone',
       'White non-Hispanic alone', 'Black alone', 'Asian alone',
       'Hispanic (any race)', 'White alone or in combination',
       'Black alone or in combination', 'Asian alone or in combination'],
      dtype=object)